name: 'Submit to Web Store 🛍️'
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup sparse checkout to exclude "images" folder
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set --no-cone '/*' '!/images/*'
          git checkout
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies and build artifact
        run: |
          cd apps/extension
          npm install
          npm run build -- --zip
          npm run build -- --zip --target=firefox-mv3
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: 'apps/extension/build/chrome-mv3-prod.zip'
          firefox-file: 'apps/extension/build/firefox-mv3-prod.zip'